#!/usr/bin/env bash
set -eu -o pipefail
# Script for generating deps files.
# Arguments are pairs of key/values
exec > "$OUTPUT_TO"
cat <<"EOF"
-- NOTE: This file is generated by bazel and linked into your workspace
-- so you can locally evaluate dhall (e.g. in your editor).
--
-- It is not required when using `bazel build`, and you SHOULD NOT
-- commit it to source control.
--
-- You can regenerate it via `bazel run {label-for-this-file}`
EOF
echo '{'
while [ "$#" -gt 0 ]; do
	name="$1"
	path="$2"
	if [ $"INLINE" = true ]; then
		value="./$path"
	else
		value="$(cat "$path")"
	fi
	echo ", \`$name\` = $value"
	shift 2
done
echo '}'
